server:
  port: 8883
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_library?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: consumer-server
test:
  url: http://localhost:8081/company/
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
